# Generated by Django 2.2.1 on 2019-06-24 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('min', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('member', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('start', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=20)),
                ('memo', models.CharField(max_length=20)),
                ('member', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('start', models.CharField(max_length=20)),
                ('goal', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('matching_1_lat', models.FloatField()),
                ('matching_1_lng', models.FloatField()),
                ('matching_1_name', models.CharField(max_length=20)),
                ('matching_2_lat', models.FloatField()),
                ('matching_2_lng', models.FloatField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs.Meeting')),
            ],
        ),
    ]
